### ISSUE TITLE
Class loads all links in a page( including link of image, advertisments, link of contents... )

### ISSUE THREAD

**Issue by doanngoctu95** [JackyAndroid/AndroidChromium#10]
I don't know where loads all links in a page( including link of image, advertisments, link of contents... ).

So can you show me what class, or where you use to load all links in a page? 

Tkanks so much!!!

**Comment by JackyAndroid** [comment]
see tab & tabmodel dir

**Comment by doanngoctu95** [comment]
Tks u, but these 2 directories have many class and method in them, ...
Can you show me specific class used to load all links in a page? 
Sr because i'm new bie so i don't have enough skill to discover problem.

If you can show me what class ( or some methods you used), tkank you so much!!!
