### ISSUE TITLE
项目精简咨询

### ISSUE THREAD

**Issue by YoungNK** [JackyAndroid/AndroidChromium#12]
我使用webview开发时候碰到有些网页打不开，想使用这个项目的基本功能来代替现在webview，想咨询项目精简是否可行和项目结构文档？

**Comment by JackyAndroid** [comment]
@ShawnSol 本项目主要目的是研究chrome源码，如果仅仅是项目需要基于webview做兼容，建议使用腾讯X5内核

**Comment by YoungNK** [comment]
谢谢建议，还是很希望研究下这个的！
