### ISSUE TITLE
App crashes on x86 devices

### ISSUE THREAD

**Issue by sufidu** [JackyAndroid/AndroidChromium#17]
Dear concern,

Thank you for your project. It's perfectly works on arm devices, but when I tried to run this app on x86 device it crashes. May be we need jniLib files for x86 devices also. 

How can I/we fixed this?

Thanks again.

**Comment by JackyAndroid** [comment]
[please see official doc to compile x86 kernel](https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md)
