### ISSUE TITLE
History Tab missing Date and Button Text

### ISSUE THREAD

**Issue by gauravk95** [JackyAndroid/AndroidChromium#18]
![rsz_screenshot_2017-02-01-19-09-36_ink_li](https://cloud.githubusercontent.com/assets/15252140/22510109/b03771a6-e8b6-11e6-9862-6edd7ef40ae0.png)

Hi, thanks for this project,

As seen above, the **Categorization of History Based on Date** and the **Button Text "CLEAR BROWSING DATA..." is missing**  from the **HISTORY TAB**(chrome://history).

Is there any way to fix this?

Thanks in Advance.

**Comment by JackyAndroid** [comment]
Thank you for your feedback, if you have time I will fix it

**Comment by JackyAndroid** [comment]
@19gauravk95 fixed
