### ISSUE TITLE
Problem in OPENING app in Nogat 7.1.1 

### ISSUE THREAD

**Issue by VishalDalve** [JackyAndroid/AndroidChromium#19]
Try to install app from Android studio 2.2.3 in debug mode on my One plus 3 device with Rom Nougat 7.1.1, but unable to Launch App (App is installing properly). Tried Manually Enable all Permissions, still same error. Do i missing something?

**Comment by JackyAndroid** [comment]
first check android studio 'instant run', if it opened, close it. About this reason, see README.
if not this reason, see detail log
