### ISSUE TITLE
关于浏览器开发

### ISSUE THREAD

**Issue by huanmingcn** [JackyAndroid/AndroidChromium#27]
我现在是大一的学生，高中有java基础，想问你一个问题，我要做一个浏览器还要懂什么知识？js？我用了一下那个CrossWalk感觉很难用，如果要使用chromium开源计划的内核，然后自己定制ui，是不是要包括chromium整个moudle？还是说谷歌有提供jar包类似腾讯x5那样？麻烦你有时间的时候一一回答一下，非常感谢

**Comment by JackyAndroid** [comment]
@hyman-lee 浏览器分好多层，看你对哪方面感兴趣了，前端、安卓、内核等，如果要做一个安卓端浏览器精通安卓然后熟悉js和内核原理就行。谷歌没有提供像腾讯那样的便利jar，整个开源项目都在chromium里面

**Comment by huanmingcn** [comment]
前端是什么?UI ?内核是WebVIew吗?

**Comment by huanmingcn** [comment]
话说chromium编译是只能一次性一起编译还是说可以分开来只编译webview?

**Comment by huanmingcn** [comment]
@JackyAndroid

**Comment by monkeydone** [comment]
如果想学一个浏览器的话,直接对chromium来说有点难了.建议先从一个基于webview的开源浏览器入手.

可以看看https://github.com/anthonycr/Lightning-Browser 这种.对浏览器有了更深入了解,再次进入chromium比较好介入.

**Comment by huanmingcn** [comment]
好的,谢谢

**Comment by JackyAndroid** [comment]
@hyman-lee 前端一般指网页UI技术，如JS、CSS、H5。浏览器内核简单理解是解析JS然后渲染成各个设备的界面，这部分基本是用C和C++实现，如V8引擎。chromium编译可以单独生成webview或者浏览器apk。

**Comment by huanmingcn** [comment]
谢谢，我先看看你推荐的那个代码
