### ISSUE TITLE
native方法在google git上的源码路径

### ISSUE THREAD

**Issue by JaydenHoFly** [JackyAndroid/AndroidChromium#32]
Jacky你好，想通过您文档中的对应关系app/src/main/jniLibs ----------- chromium/src/out/gnbuild/，寻找对应源码，但是找了一天都没有找到这个目录，out目录是否是编译后才会生成呢。非常冒昧用提issue的方式跟您沟通，但是没有找到其他的沟通方式，如果打扰到你了，非常抱歉。

**Comment by JackyAndroid** [comment]
@JaydenHoFly 应该是先配置生成目录，然后再编译，配置的时候out目录应该就生成了，具体方法查看chromium社区

**Comment by JaydenHoFly** [comment]
非常感谢您的回复，我把源码编译一下试试看，谢谢。
