### ISSUE TITLE
can't open browser and crash

### ISSUE THREAD

**Issue by menshen** [JackyAndroid/AndroidChromium#36]
06-13 17:44:48.769   669   669 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider org.chromium.chrome.browser.provider.ChromeBrowserProvider: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.chromium.base.BaseChromiumApplication
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5369)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4887)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4818)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:168)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:150)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5665)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
06-13 17:44:48.769   669   669 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.chromium.base.BaseChromiumApplication
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at org.chromium.base.BaseChromiumApplication.initCommandLine(BaseChromiumApplication.java:145)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at org.chromium.chrome.browser.provider.ChromeBrowserProvider.onCreate(ChromeBrowserProvider.java:246)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5366)
06-13 17:44:48.769   669   669 E AndroidRuntime: 	... 10 more

**Comment by JackyAndroid** [comment]
duplicate #7
