### ISSUE TITLE
如何开启浏览器的全屏模式

### ISSUE THREAD

**Issue by WHHHH** [JackyAndroid/AndroidChromium#41]
你好，我在学习您的 AndroidChromium 项目时遇到一个问题，还望指导一下。

问题如下：在外部应用通过 intent 的方式打开全屏模式的浏览器时，如何满足它的判断条件。

文件路径：webapps/WebappLauncherActivity.java
判断条件：
String **webappMac** = IntentUtils.safeGetStringExtra(intent, ShortcutHelper.EXTRA_MAC);

if (validWebApk || **isValidMacForUrl**(webappUrl, webappMac) || wasIntentFromChrome(intent)) {

为了满足 isValidMacForUrl 函数要求，这个 ShortcutHelper.EXTRA_MAC，我在外部应该如何生成。一番查阅后我在以下文件找到了这样的函数。

文件路径：browser/ShortcutHelper.java
函数：（根据 url 生成 mac）
public static String getEncodedMac(Context context, String url) {

当我把此函数以及它所涉及到的相关类全部移植到外部应用中使用时发现一个问题：

同一个 url 地址，在不同应用中计算出来的值是不一样的！那么问题来了，如果这个函数算法不能算出一个 url 和 mac 的固定值，那么其他外部应用岂不是不可能通过这个判断条件来打开全屏模式的浏览器？那这个判断条件存在的意义是什么？我不知道是我使用的方式不对还是说这可能是个bug？在此恳请您指点一下方向。

第一次提问题，有点啰嗦，还望见谅。

**Comment by JackyAndroid** [comment]
@WHHHH 我的理解是这样的，无论什么样的验证条件，都是为了保证是在chrome中添加到桌面的。也就是说，如果想在自己的App中添加到桌面，而且想在点击的时候使用chrome打开，那就研究chrome添加到桌面的逻辑，里面应该会加一些验证条件的，用于下一次打开的时候验证。
