### ISSUE TITLE
获取不到某视频网站的视频链接？

### ISSUE THREAD

**Issue by ZhangKuixun** [JackyAndroid/AndroidChromium#46]
作者你好？

    我需要使用你的androidChromium访问各个视频网站获取视频链接。有的视频链接能从RemoteMediaPlayerBridge.create(...,String sourceUrl, ..., ....)的sourceUrl返回。但是有的视频网站无法从create返回正确的URL，比如：video.fc2.com的视频链接无法从create方法返回正确的sourceUrl，可是视频能播放，获取不到正确的sourceUrl。我在你的项目中查找video.fc2.com类似的正确视频sourceUrl，已经查找了4天了，始终没有结果，望作者回复？

**Comment by JackyAndroid** [comment]
@ZhangKuixun 有的视频网站在技术上做了封锁，没办法直接获取url，就像不能自动跳过广告一样
