### ISSUE TITLE
Can not play video on sohu.com

### ISSUE THREAD

**Issue by uplusplus** [JackyAndroid/AndroidChromium#50]
adndroid system: 4.4.2
websit: sohu.com

error log:
11-29 11:09:23.350 111-12969/? E/AudioSink: received unknown event type: 1 inside CallbackWrapper !
11-29 11:09:23.370 111-12972/? E/FFMpegMediaPlayer: Hery,.....delete -83991908
11-29 11:09:23.380 111-12972/? E/FFMpegMediaPlayer: Hery,.....delete -83991908
11-29 11:09:23.380 111-12972/? E/FFMpegMediaPlayer: Hery,.....delete -83991908
11-29 11:09:23.390 111-12972/? E/FFMpegMediaPlayer: Hery,.....delete -83991908
11-29 11:09:23.400 111-12972/? E/FFMpegMediaPlayer: Hery,.....delete -83991908
11-29 11:09:23.400 111-12972/? E/FFMpegMediaPlayer: FF_MediaPlayer::initRender:mControlBufferSize=1
11-29 11:09:23.620 111-12960/? E/FFMpegMediaPlayer: hls_seek:tm=0,curQ=5
11-29 11:09:23.620 111-12960/? E/FFMpegMediaPlayer: finished HLS read data AVERROR_EOF
11-29 11:09:23.620 111-12960/? E/FFMpegMediaPlayer: finished HLS read data AVERROR_EOF
11-29 11:09:23.620 111-12960/? E/FFMpegMediaPlayer: HLS read AVERROR_EOF
11-29 11:09:23.780 111-12960/? E/FFMpegMediaPlayer: hls_seek:tm=0,curQ=5
11-29 11:09:23.780 111-12960/? E/FFMpegMediaPlayer: finished HLS read data AVERROR_EOF
11-29 11:09:23.780 111-12960/? E/FFMpegMediaPlayer: finished HLS read data AVERROR_EOF
11-29 11:09:23.780 111-12960/? E/FFMpegMediaPlayer: HLS read AVERROR_EOF
11-29 11:09:25.920 111-12960/? E/FFMpegMediaPlayer: hls_seek:tm=0,curQ=5
11-29 11:09:25.920 111-12960/? E/FFMpegMediaPlayer: finished HLS read data AVERROR_EOF
11-29 11:09:25.920 111-12960/? E/FFMpegMediaPlayer: finished HLS read data AVERROR_EOF
11-29 11:09:25.920 111-12960/? E/FFMpegMediaPlayer: HLS read AVERROR_EOF

**Comment by JackyAndroid** [comment]
@uplusplus This should belong to Native error, see the Java layer error

**Comment by JackyAndroid** [comment]
non-response , close
