### ISSUE TITLE
Could not find class 

### ISSUE THREAD

**Issue by lyqaiym** [JackyAndroid/AndroidChromium#53]
4.4.2系统

ailed resolving Lorg/chromium/chrome/browser/provider/ChromeBrowserProvider$1; interface 8207 'Lorg/chromium/content/browser/BrowserStartupController$StartupCallback;'
02-06 12:56:07.044: W/dalvikvm(30028): Link of class 'Lorg/chromium/chrome/browser/provider/ChromeBrowserProvider$1;' failed
02-06 12:56:07.044: E/dalvikvm(30028): Could not find class 'org.chromium.chrome.browser.provider.ChromeBrowserProvider$1', referenced from method org.chromium.chrome.browser.provider.ChromeBrowserProvider.onCreate
02-06 12:56:07.044: W/dalvikvm(30028): VFY: unable to resolve new-instance 7356 (Lorg/chromium/chrome/browser/provider/ChromeBrowserProvider$1;) in Lorg/chromium/chrome/browser/provider/ChromeBrowserProvider;
02-06 12:56:07.044: D/dalvikvm(30028): VFY: replacing opcode 0x22 at 0x0010
02-06 12:56:07.044: I/dalvikvm(30028): Failed resolving Lorg/chromium/chrome/browser/provider/ChromeBrowserProvider$1; interface 8207 'Lorg/chromium/content/browser/BrowserStartupController$StartupCallback;'
02-06 12:56:07.044: W/dalvikvm(30028): Link of class 'Lorg/chromium/chrome/browser/provider/ChromeBrowserProvider$1;' failed
02-06 12:56:07.044: D/dalvikvm(30028): DexOpt: unable to opt direct call 0xd873 at 0x12 in Lorg/chromium/chrome/browser/provider/ChromeBrowserProvider;.onCreate
02-06 12:56:07.044: E/dalvikvm(30028): Could not find class 'org.chromium.content.browser.BrowserStartupController$2', referenced from method org.chromium.content.browser.BrowserStartupController.enqueueCallbackExecution
02-06 12:56:07.044: W/dalvikvm(30028): VFY: unable to resolve new-instance 8204 (Lorg/chromium/content/browser/BrowserStartupController$2;) in Lorg/chromium/content/browser/BrowserStartupController;
02-06 12:56:07.044: D/dalvikvm(30028): VFY: replacing opcode 0x22 at 0x0005
02-06 12:56:07.054: E/dalvikvm(30028): Could not find class 'org.chromium.content.browser.BrowserStartupController$StartupCallback', referenced from method org.chromium.content.browser.BrowserStartupController.executeEnqueuedCallbacks
02-06 12:56:07.054: W/dalvikvm(30028): VFY: unable to resolve check-cast 8207 (Lorg/chromium/content/browser/BrowserStartupController$StartupCallback;) in Lorg/chromium/content/browser/BrowserStartupController;
02-06 12:56:07.054: D/dalvikvm(30028): VFY: replacing opcode 0x1f at 0x002a
02-06 12:56:07.054: I/dalvikvm(30028): Could not find method org.chromium.content.browser.PepperPluginManager.getPlugins, referenced from method org.chromium.content.browser.BrowserStartupController.getPlugins
02-06 12:56:07.054: W/dalvikvm(30028): VFY: unable to resolve static method 62473: Lorg/chromium/content/browser/PepperPluginManager;.getPlugins (Landroid/content/Context;)Ljava/lang/String;
02-06 12:56:07.054: D/dalvikvm(30028): VFY: replacing opcode 0x71 at 0x0002
02-06 12:56:07.054: E/dalvikvm(30028): Could not find class 'org.chromium.content.browser.BrowserStartupController$3', referenced from method org.chromium.content.browser.BrowserStartupController.postStartupCompleted
02-06 12:56:07.054: W/dalvikvm(30028): VFY: unable to resolve new-instance 8205 (Lorg/chromium/content/browser/BrowserStartupController$3;) in Lorg/chromium/content/browser/BrowserStartupController;
02-06 12:56:07.054: D/dalvikvm(30028): VFY: replacing opcode 0x22 at 0x0005
02-06 12:56:07.054: E/dalvikvm(30028): Could not find class 'org.chromium.content.browser.BrowserStartupController$4', referenced from method org.chromium.content.browser.BrowserStartupController.prepareToStartBrowserProcess
02-06 12:56:07.054: W/dalvikvm(30028): VFY: unable to resolve new-instance 8206 (Lorg/chromium/content/browser/BrowserStartupController$4;) in Lorg/chromium/content/browser/BrowserStartupController;
02-06 12:56:07.054: D/dalvikvm(30028): VFY: replacing opcode 0x22 at 0x002c
02-06 12:56:07.054: E/dalvikvm(30028): Could not find class 'org.chromium.content.browser.BrowserStartupController$1', referenced from method org.chromium.content.browser.BrowserStartupController.startBrowserProcessesAsync
02-06 12:56:07.054: W/dalvikvm(30028): VFY: unable to resolve new-instance 8203 (Lorg/chromium/content/browser/BrowserStartupController$1;) in Lorg/chromium/content/browser/BrowserStartupController;
02-06 12:56:07.054: D/dalvikvm(30028): VFY: replacing opcode 0x22 at 0x002e

**Comment by JackyAndroid** [comment]
使用了instant run 或者其他的加速编译工具吗？
