### ISSUE TITLE
求教如何修改userAgent

### ISSUE THREAD

**Issue by Martian-me** [JackyAndroid/AndroidChromium#59]
本人非android开发者，由于在意隐私，一直想自己编译一个浏览器用，刚好找到这个。这个工程我clone下来也编译成功运行了。我希望我每次打开网页时，http 请求 header 中的 userAgent 能是随机的非真实的，没有找到哪里能改了，代码里搜 userAgent 搜出来的地方改了似乎都不凑效，希望作者能指点一二

**Comment by JackyAndroid** [comment]
试下 Tab#setUseDesktopUserAgent 看看能不能满足你的需求

**Comment by Martian-me** [comment]
> 试下 Tab#setUseDesktopUserAgent 看看能不能满足你的需求

感谢回复。似乎这个方法只是把ua设置成桌面浏览器的，并不是能设置成任意我指定的。我是希望能设置成任意我指定的字符串。
