### ISSUE TITLE
求教关于历史记录，以及定制UI

### ISSUE THREAD

**Issue by DorisGM** [JackyAndroid/AndroidChromium#61]
你好，我在看UI定制的过程中，发现你的工程目录下相对源码少了history 这个目录，但是其实历史记录可以正常使用。是放在了别的地方了吗？  
 对于UI定制，请教有没有相关的资料可以学习？ 看了一下网上没找到呢。 如能回复，感激

**Comment by JackyAndroid** [comment]
历史记录是有的，界面定制如果网上没有，只能自己研究
