### ISSUE TITLE
Update to version 70

### ISSUE THREAD

**Issue by AviFix** [JackyAndroid/AndroidChromium#64]
Hi,

Thanks for this project.

Could you please update to the last chromium version (70)?

Thanks
Avi

**Comment by JackyAndroid** [comment]
@AviFix sorry , I don't have a high-performance machine that compiles the kernel recently

**Comment by Lua12138** [comment]
I can provide a machine to help you compile, up to 24G of memory, 24 cores with a maximum frequency of 3.2Ghz. If you have free time.

**Comment by JackyAndroid** [comment]
@gam2046 thanks , your machine is cloud server?

**Comment by AviFix** [comment]
Any change for an update?

**Comment by JackyAndroid** [comment]
@AviFix no machine.🙁

**Comment by AviFix** [comment]
What kind of machine (exactly) do you need and for how long?
I'll check it cost on Amazon

**Comment by JackyAndroid** [comment]
i7 16G memory 100G ssd one week.

**Comment by AviFix** [comment]
How can I contact you?

**Comment by JackyAndroid** [comment]
jacky.android@foxmail.com
