### ISSUE TITLE
AndroidStudio3.0+ build failed

### ISSUE THREAD

**Issue by XunMengWinter** [JackyAndroid/AndroidChromium#68]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ice/Android/GitHub/AndroidChromium-master/app/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method enforceUniquePackageName() for arguments [false] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 12s
ERROR: Could not find method enforceUniquePackageName() for arguments [false] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.
Open File

**Comment by rahulkumarsingh73690** [comment]
This is Old Source Code and Not Comfortable with the latest version of android studio. For Latest code check this official guide - https://chromium.googlesource.com/chromium/src/+/master/docs/get_the_code.md

**Comment by JackyAndroid** [comment]
@XunMengWinter I am using AS 3.3.2, there is no problem running the project, have you upgraded the gradle version?
