### ISSUE TITLE
怎样获取libchrome.so

### ISSUE THREAD

**Issue by carina-wyw** [JackyAndroid/AndroidChromium#69]
因分享视频需求，需要修改编译参数，参考https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md中Multiple Chrome APK Targets部分，使用chrome_modern_public_apk编译，编译完成后只在out目录找到libchrome.cr.so，解压apk后找到的也是libchrome.cr.so，没有找到libchrome.so。请问如何能获取libchrome.so文件？谢谢！

**Comment by JackyAndroid** [comment]
那应该是没有编译成功把，so就在out目录下面

**Comment by carina-wyw** [comment]
感谢回答，已经解决，参考https://groups.google.com/a/chromium.org/forum/#!searchin/android-webview-dev/libchrome.so%7Csort:date/android-webview-dev/qfCSdw2zwXQ/N65VzEmSEgAJ 修改编译参数is_debug=false and is_official_build=true，编译完成后可以整合的libchrome.so，否则得到的是很多独立的so。
