### ISSUE TITLE
如何替换项目中libchrome.so

### ISSUE THREAD

**Issue by carina-wyw** [JackyAndroid/AndroidChromium#72]
下载了https://github.com/dummas2008/AndroidChromium 项目并且运行正常。
现因视频通话需求，需要设置H264等属性后，重新编译获取libchrome.so.
根据AndroidChromium项目说明chromium版本是 70.0.3538.64，运行git checkout 70.0.3538.64，gclient sync --with_branch_heads --with_tags，并设置编译参数is_debug=false ， is_official_build=true 和target_os="android"，之后autoninja -C out/Default chrome_modern_public_apk，完成后使用out目录下的libchrome.so和libchromium_android_linker.so替换原项目中的so，结果出现加载网页时停止运行。（并且编译参数增加 ffmpeg_branding="Chrome" enable_ffpmeg_video_decoders=true proprietary_codecs=true use_gold=false use_lld=true'也会停止运行）错误如下：

2019-04-24 13:47:59.292 943-10735/system_process D/AES: onEndOfErrorDumpThread: data_app_native_crash Process: com.tpv.xmic.vc.pd
    Flags: 0x38c8bf46
    Package: com.tpv.xmic.vc.pd v2019041601 (2019041601)
    Foreground: Yes
    Build: Philips/X828/X828_RU:7.0/NRD90M/1530715648:userdebug/release-keys
    
    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'Philips/X828/X828_RU:7.0/NRD90M/1530715648:userdebug/release-keys'
    Revision: '0'
    ABI: 'arm'
    pid: 10477, tid: 10477, name: .tpv.xmic.vc.pd  >>> com.tpv.xmic.vc.pd <<<
    signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xcaa59f4f
        r0 ef67eb68  r1 cba0a661  r2 42f75b24  r3 cbbaa82f
        r4 00000000  r5 cdbb9520  r6 ffffffff  r7 00000000
        r8 ca417180  r9 ef605400  sl ef67eb30  fp ffcca954
        ip cd424404  sp ffcca5f0  lr cba0b219  pc cba0a660  cpsr 600d0030
    
    backtrace:
        #00 pc 01466660  /data/app/com.tpv.xmic.vc.pd-2/lib/arm/libchrome.so (offset 0x868000)
        #01 pc 01467217  /data/app/com.tpv.xmic.vc.pd-2/lib/arm/libchrome.so (offset 0x868000)
        #02 pc 01f6bacb  /data/app/com.tpv.xmic.vc.pd-2/lib/arm/libchrome.so (offset 0x868000)
        #03 pc 01466d39  /data/app/com.tpv.xmic.vc.pd-2/lib/arm/libchrome.so (offset 0x868000)
        #04 pc 01f00c3d  /data/app/com.tpv.xmic.vc.pd-2/oat/arm/base.odex (offset 0x1d30000)
     10477
2019-04-24 13:47:59.292 943-10735/system_process W/AES: Exception Log handling...
2019-04-24 13:47:59.293 943-10735/system_process D/AES: ExceptionLog: notify aed
2019-04-24 13:47:59.293 943-10735/system_process D/AES:     process : com.tpv.xmic.vc.pd
2019-04-24 13:47:59.293 943-10735/system_process D/AES:      module : com.tpv.xmic.vc.pd v2019041601 (2019041601)
2019-04-24 13:47:59.293 943-10735/system_process D/AES:       cause : data_app_native_crash
2019-04-24 13:47:59.293 943-10735/system_process D/AES:       pid : 10477
2019-04-24 13:47:59.294 943-10735/system_process W/AES: native_crash should be processed by aee already

出现以上问题是什么原因呢？

**Comment by JackyAndroid** [comment]
你 clone 的是https://github.com/dummas2008/AndroidChromium？

**Comment by syzhugh** [comment]
想请问一下，编译libchrome.so对分析这种crash是否有帮助呢 ？ @carina-wyw car @JackyAndroid 
`
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Crash type: 'native'
Start time: '2021-12-12T19:27:04.220-0300'
Crash time: '2021-12-12T23:36:23.479-0300'
Rooted: 'No'
API level: '28'
OS version: '9'
Kernel version: 'Linux version 3.18.120-perf-g3e480e17e11f-04280-g407726838ebf #1 SMP PREEMPT Sat Apr 4 12:24:37 CDT 2020 (armv7l)'
ABI list: 'armeabi-v7a,armeabi'
Manufacturer: 'motorola'
Brand: 'motorola'
Model: 'moto g(6) play'
Build fingerprint: 'motorola/aljeter/aljeter:9/PPPS29.55-35-18-7/6a0d0:user/release-keys'
ABI: 'arm'
pid: 4903, tid: 5460, name: RenderThread  >>> *** <<<
signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
    r0  00000000  r1  00000000  r2  00000000  r3  8f06fad6
    r4  6d9de8b4  r5  00000046  r6  6d9de46c  r7  92a671d0
    r8  a59f1498  r9  a59f6d8c  r10 6d9de8bc  r11 00000000
    ip  92a00d14  sp  6d9de458  lr  90d18467  pc  9109407c

backtrace:
    #00 pc 0248607c  /data/app/com.android.chrome-LDqcEO_Q2mIwG_D85cQIvQ==/base.apk!/lib/armeabi-v7a/libmonochrome.so
    #01 pc 00d19556  /data/app/com.android.chrome-LDqcEO_Q2mIwG_D85cQIvQ==/base.apk!/lib/armeabi-v7a/libmonochrome.so
    #02 pc 02f9694e  /data/app/com.android.chrome-LDqcEO_Q2mIwG_D85cQIvQ==/base.apk!/lib/armeabi-v7a/libmonochrome.so
    #03 pc 02b46cac  /data/app/com.android.chrome-LDqcEO_Q2mIwG_D85cQIvQ==/base.apk!/lib/armeabi-v7a/libmonochrome.so
`

**Comment by JackyAndroid** [comment]
@syzhugh 可以尝试下
