### ISSUE TITLE
访问外文网页时，TranslateInfoBar.show不调用

### ISSUE THREAD

**Issue by wall3001** [JackyAndroid/AndroidChromium#74]
TranslateInfoBar.show(int translateBarType, String sourceLanguageCode,String targetLanguageCode, boolean autoTranslatePair, boolean showNeverInfobar,boolean triggeredFromMenu, String[] languages, String[] codes)
这个方法怎么没调用？我下载的官方的app是可以的。

**Comment by JackyAndroid** [comment]
首先官方chrome 和 chromium是两个项目，详细描述下
