### ISSUE TITLE
多窗口切换保存问题

### ISSUE THREAD

**Issue by why168** [JackyAndroid/AndroidChromium#8]
最近在开发浏览器，你可以给我点思路吗？

**Comment by JackyAndroid** [comment]
@why168 浏览器难点也就在tab管理这一块，做的最好的是chrome从数据层面进行优化。不过就国内的浏览器来说，大家还是业务为主，基本都是从UI层去限制tab，这样就简单很多。
我建议也是从UI层去限制tab的行为，如果产品必须要无限制加tab而且内存还要优化的很好，可以参考本项目源码。

**Comment by why168** [comment]
从UI层去限制tab，用什么控件操作呢？
