### ISSUE TITLE
如何把浏览器封装一个app

### ISSUE THREAD

**Issue by windouxp** [JackyAndroid/AndroidChromium#80]
如题，我想启动app就显示自己定义的主页。没有搜索栏没有其他东西  直接就是加载了一个网页的app。大佬能不能给点思路

**Comment by SmallRedSister** [comment]
联系我吧！最近在研究这个，QQ：2279833535

**Comment by windouxp** [comment]
> 联系我吧！最近在研究这个，QQ：2279833535

我不用这个了，用腾讯x5浏览器内核了 ，也是基于chromium的  虽然不能改源码
